'use strict';
let fullName = 'Vanessa Viray';
let isCool = true;
let totalPets = 1;
console.log('value of fullName:', fullName);
console.log('value of isCool:', isCool);
console.log('value of totalPets:', totalPets);
console.log('typeof fullName:', typeof fullName);
console.log('typeof isCool:', typeof isCool);
console.log('typeof totalPets:', typeof totalPets);
let empty = null;
console.log('value of empty:', empty);
console.log('typeof empty:', typeof empty);
let nothing;
console.log('value of nothing:', nothing);
console.log('typeof nothing:', nothing);
