'use strict';
let width = 4;
let height = 6;
let area = width * height;
console.log('value of area:', area);
console.log('typeof area:', typeof area);
let bill = 12;
let payment = 20;
let change = payment - bill;
console.log('value of change:', change);
console.log('typeof change:', typeof change);
let quizzes = 100;
let midterm = 94;
let final = 97;
let grade = (quizzes + midterm + final) / 3;
console.log('value of grade:', grade);
console.log('typeof grade:', typeof grade);
let firstName = 'Vanessa';
let lastName = 'Viray';
let fullName = firstName + ' ' + lastName;
console.log('value of fullName:', fullName);
console.log('typeof fullName:', typeof fullName);
let pH = 8;
let isAcidic = pH < 7;
console.log('value of isAcidic:', isAcidic);
console.log('typeof isAcidic:', typeof isAcidic);
let headCount = 150;
let isSparta = headCount === 300;
console.log('value of isSparta:', isSparta);
console.log('typeof isSparta:', typeof isSparta);
let motto = fullName;
motto += ' is the GOAT';
console.log('value of motto:', motto);
console.log('typeof motto:', typeof motto);
